export const chapters = {
  2: {
    id: 2,
    label: "PART II",
    route: "CHICAGO → ALBUQUERQUE",
    dates: "Aug 21–31, 2026",
    intro: "The road continues west.",
    hero: "/assets/part2/route66-part2-hero.png",
    heroAlt: "Pixel-art rental car heading west on Route 66 across the Illinois prairie",
  },
  1: {
    id: 1,
    label: "PART I",
    route: "SANTA MONICA → ALBUQUERQUE",
    dates: "Feb 12–21, 2026",
    intro: "The first saved game: California to New Mexico.",
    hero: "/assets/part1/route66-part1-hero.png",
    heroAlt: "Pixel-art Route 66 journey from the Pacific coast toward the New Mexico desert",
  },
};

export const entries = [
  {
    part: 2,
    day: 4,
    slug: "lincoln-miles-of-memories-cozy-dog-st-louis",
    title: "Lincoln, Miles of Memories & St. Louis",
    date: "2026-08-24",
    dateDisplay: "Aug 24, 2026",
    location: "St. Louis, Missouri",
    weather: "Sunny, 26/12°C.",
    summary: "A final Lincoln morning, an enormous Route 66 centennial exhibition, the original Cozy Dog story, roadside giants, and a late-afternoon run into St. Louis.",
    image: "/assets/part2/day4-springfield-st-louis.webp",
    imageAlt: "Pixel-art cream road-trip sedan passing Springfield landmarks and Cozy Dog on Route 66 toward the St. Louis Gateway Arch",
    imageCaption: "SPRINGFIELD → ST. LOUIS · A CENTURY OF ROAD",
    body: [
      "Day 4 began by finishing the Lincoln stops we could not squeeze into yesterday. Lincoln Home made the president feel less like a monument and more like a real Springfield neighbor—with a busy household, troublesome children, and a life waiting just beyond the front door.",
      "Lincoln Tomb shifted the mood completely. The stovepipe hat, the rail-splitter mythology, and all the familiar Honest Abe stories suddenly led to one quiet place, making the morning feel much heavier than a normal roadside checklist.",
      "Then the Illinois State Museum's Miles of Memories exhibition turned out to be huge. Colored Depression glass, cinder goggles, a Nash Tower of Value, a Crosley Hotshot, coffee makers, phonograph cylinders, and enough Route 66 artifacts to make a century of roadside history feel like one extremely crowded family attic.",
      "Cozy Dog Drive-In brought us back to the essential road-trip questions: how to order, whether this counts as the invention of the corn dog, and why food on a stick tastes more historically important beside Route 66. We also found the Route Dog and paid our respects to Springfield's flag-holding Lauterbach Giant.",
      "By late afternoon the cream sedan was pointed south toward St. Louis. The Gateway Arch appeared ahead like the next level's title screen, and we checked into the Hampton Inn downtown—close enough to the riverfront to start asking how a 1965 monument became the symbol of westward expansion before we had even unpacked.",
    ],
    stops: ["Lincoln Home", "Lincoln Tomb", "Illinois State Museum · Miles of Memories", "Cozy Dog Drive-In", "Route Dog", "Lauterbach Giant", "Route 66 to St. Louis", "Hampton Inn St. Louis-Downtown"],
  },
  {
    part: 2,
    day: 3,
    slug: "pontiac-murals-lincolns-springfield",
    title: "Murals, Museums & Lincoln's Springfield",
    date: "2026-08-23",
    dateDisplay: "Aug 23, 2026",
    location: "Springfield, Illinois",
    weather: "Sunny, 26/13°C.",
    summary: "Pontiac museums and murals, a bridge that moves under your feet, roadside giants, Lincoln history, and a Springfield hotel arrival with unfortunate Kickback timing.",
    image: "/assets/part2/day3-pontiac-springfield.png",
    imageAlt: "Pixel-art Pontiac mural and swinging bridge leading toward Springfield's capitol dome",
    imageCaption: "PONTIAC · ROAD-DAY MORNING",
    body: [
      "Day 3 began with a glamorous rental-car subplot: a low tire. We added air, watched the number like responsible adults, and unlocked a new Route 66 achievement—roadside maintenance before breakfast.",
      "Pontiac was worth the pause. We worked through the Route 66 Hall of Fame Museum and the Pontiac-Oakland Museum, then followed the Walldogs murals around downtown like a scavenger hunt designed by people with very strong feelings about brick walls.",
      "The so-called Swinging Bridge turned out not to swing open at all. It is a narrow suspension footbridge, and the deck moves just enough under your feet to make the crossing feel more adventurous than the map suggested.",
      "After a Wally's stop for the full wall-of-jerky and popcorn-flavor experience, we met Atlanta's Paul Bunyan holding his giant hot dog and continued toward Springfield. Closing time won the race, turning Lincoln Home and Lincoln Tomb into tomorrow morning's first mission.",
      "We checked into Drury Inn & Suites Springfield and learned the cruelest hotel lesson of the trip: the 5:30 Kickback does not wait for anyone. At least we were finally in Lincoln—and Cozy Dog—territory, with the unfinished stops lined up for Day 4.",
    ],
    stops: ["Pontiac Route 66 Hall of Fame Museum", "Pontiac-Oakland Museum", "Pontiac mural district", "Swinging Bridges", "Wally's Pontiac", "Atlanta Paul Bunyan", "Springfield arrival", "Drury Inn & Suites Springfield"],
  },
  {
    part: 2,
    day: 2,
    slug: "lou-mitchells-joliet-gemini-giant",
    title: "Lou Mitchell's, Joliet & the Gemini Giant",
    date: "2026-08-22",
    dateDisplay: "Aug 22, 2026",
    location: "Pontiac, Illinois",
    weather: "Cool and partly cloudy, 22/14°C.",
    summary: "A dawn landing at O'Hare, classic diner fuel, Chicago and Joliet detours, the Gemini Giant, and the first real stretch of the Mother Road.",
    image: "/assets/part2/day2-joliet-pontiac.png",
    imageAlt: "Pixel-art Illinois Route 66 roadside scene with a giant spaceman and rental car",
    imageCaption: "ILLINOIS · THE MOTHER ROAD BEGINS",
    body: [
      "We landed at O'Hare before the city was properly awake, collected the Hertz car, and officially upgraded the trip from airport mode to road-trip mode.",
      "Breakfast at Lou Mitchell's was exactly the kind of old-school launch Route 66 deserves: coffee, diner energy, and enough history in the room to make our overnight flight feel almost respectable.",
      "We made a quick Chicago pass for the Route 66 beginning-of-the-road ritual, then aimed southwest toward Joliet. The welcome center, the Rialto exterior, and the old prison turned one stop into several because apparently we are incapable of merely driving through a historic town.",
      "The Gemini Giant was waiting in Wilmington with an American flag and a rocket, looking like roadside America had hired its own space program. This is the kind of completely unnecessary monument that makes Route 66 absolutely necessary.",
      "We added the restored Standard Oil station in Odell, then rolled into Pontiac for the night at the Hampton Inn—tired enough to stop, but already surrounded by murals and museum signs clearly plotting tomorrow's schedule.",
    ],
    stops: ["O'Hare International Airport", "Lou Mitchell's", "Route 66 Begin Sign", "Joliet Route 66 Welcome Center", "Rialto Square Theatre", "Old Joliet Prison", "Gemini Giant", "Odell Standard Oil Station", "Hampton Inn Pontiac"],
  },
  {
    part: 2,
    day: 1,
    slug: "red-eye-to-route-66",
    title: "Red-Eye to Route 66",
    date: "2026-08-21",
    dateDisplay: "Aug 21, 2026",
    location: "San Francisco → Chicago",
    weather: "Clear night, 18/13°C.",
    summary: "Part II begins with CLEAR, carry-ons, a late gate upgrade sighting, and an overnight flight pointed straight at Chicago.",
    image: "/assets/part2/day1-red-eye.png",
    imageAlt: "Pixel-art late-night airport gate with an airplane waiting outside",
    imageCaption: "DEPARTURE · 10:53 PM",
    body: [
      "Part II of Route 66 began with the bold frontier move of taking an overnight flight from San Francisco to Chicago. The pioneers had wagons; we had boarding groups and a very specific carry-on strategy.",
      "CLEAR and TSA PreCheck moved fast at SFO, which gave us just enough time to settle into airport life and watch everyone perform the ancient ritual of staring at the gate screen even though it had not changed.",
      "American Airlines flight AA2113 was scheduled for 10:53 p.m., with Chicago waiting at 5:13 in the morning. The official plan was to sleep. The realistic plan was to negotiate with an economy seat until sunrise.",
      "Near the end of boarding, we watched a last-minute upgrade happen at the gate—a tiny burst of first-class drama while the rest of us continued our brave march toward row 22.",
      "Tomorrow: O'Hare, a rental car, Lou Mitchell's, and actual Route 66 pavement. Tonight: cabin lights, airplane air, and the opening credits.",
    ],
    stops: ["San Francisco International Airport", "American Airlines AA2113", "Chicago O'Hare International Airport"],
  },
  {
    part: 1,
    day: 10,
    slug: "folk-art-fancy-coffee-bye-new-mexico",
    title: "Folk Art, Fancy Coffee, Bye New Mexico",
    date: "2026-02-21",
    dateDisplay: "Feb 21, 2026",
    location: "Albuquerque",
    weather: "Mostly cloudy, 15/-5°C.",
    summary: "Breakfast at Hotel Santa Fe, a stop at the Museum of International Folk Art, coffee at Iconik Lupe, then to ABQ for the flight leg back to PHX and SFO.",
    image: "/assets/part1/day10-santa-fe-albuquerque.webp",
    imageAlt: "Pixel-art Santa Fe folk-art courtyard and coffee stop leading toward Albuquerque airport",
    imageCaption: "SANTA FE → ALBUQUERQUE · FINAL LEG",
    body: [
      "We started the morning by doing the rarest thing on any trip: actually enjoying hotel breakfast.",
      "Hotel Santa Fe came through with a legit breakfast spread, good coffee, and zero regrets. Honestly, it set an unreasonably high bar for the rest of the day.",
      "From there we headed to the Museum of International Folk Art and wandered through room after room of pieces that somehow made us feel both cultured and underdressed.",
      "Then came the coffee mission in Lupe: the spot is Iconik Lupe on Guadalupe. Famous for a reason—strong coffee, cool vibe, and exactly the right amount of “we should probably be heading out” energy.",
      "After that, we made the push to ABQ (Albuquerque International Sunport) and got ready to fly back toward PHX and then SFO. Route 66 ground mission complete; airport mode activated.",
    ],
    stops: ["Hotel Santa Fe", "Museum of International Folk Art", "Iconik Lupe", "Albuquerque International Sunport"],
  },
  {
    part: 1,
    day: 9,
    slug: "downtown-santa-fe-miracle-staircase-happy-hour-timing",
    title: "Downtown Santa Fe Wandering, Miracle Staircase, and Happy Hour Timing",
    date: "2026-02-20",
    dateDisplay: "Feb 20, 2026",
    location: "Santa Fe",
    weather: "Sunny, 6/-9°C.",
    summary: "A downtown Santa Fe day with the Loretto miracle staircase, enchiladas and green chile stew, San Miguel Chapel, Canyon Road galleries, and a strategic happy-hour return.",
    image: "/assets/part1/day9-santa-fe-wandering.webp",
    imageAlt: "Pixel-art Santa Fe adobe streets with Loretto Chapel, galleries, and winter sunlight",
    imageCaption: "SANTA FE · DOWNTOWN WANDERING",
    body: [
      "Today was supposed to be a “light” day, which naturally turned into a full mission with a lot of walking and very confident snack logic.",
      "We spent most of the day wandering downtown Santa Fe, people-watching, ducking in and out of shops, and pretending we were “just browsing” while absolutely power-touring everything within a few blocks.",
      "We stopped at Loretto Chapel to see the famous miracle staircase in person. I can confirm: photos do not do it justice, and yes, everyone there has the same expression of “wait… how did they even build this?”",
      "Lunch was a proper New Mexico move at The Shed—enchiladas plus green chile stew, which was exactly the kind of meal that makes you rethink every bland lunch choice you've made in your life.",
      "After that we checked out San Miguel Chapel, then made our way through the Canyon Road art district. Lots of galleries, lots of “we should totally hang this at home” moments, and a shocking amount of self-control.",
      "We wrapped the day by heading back to Hotel Santa Fe with perfect timing for happy hour, which is the kind of elite logistical execution this trip deserves.",
    ],
    stops: ["Downtown Santa Fe", "Loretto Chapel", "The Shed", "San Miguel Chapel", "Canyon Road", "Hotel Santa Fe"],
  },
  {
    part: 1,
    day: 8,
    slug: "winslow-to-santa-fe-wigwam-throwback-maverik-save",
    title: "Winslow to Santa Fe, Wigwam Throwback, and a Maverik Save",
    date: "2026-02-19",
    dateDisplay: "Feb 19, 2026",
    location: "Santa Fe",
    weather: "Light snow, 2/-6°C.",
    summary: "Long haul from Winslow to Santa Fe with Wigwam nostalgia, a Maverik fuel save, a first Dairy Queen upside-down ice cream moment, and a cozy two-night stay at Hotel Santa Fe.",
    image: "/assets/part1/day8-winslow-santa-fe.webp",
    imageAlt: "Pixel-art Route 66 drive from Winslow past a wigwam motel toward snowy Santa Fe",
    imageCaption: "WINSLOW → SANTA FE · LONG HAUL",
    body: [
      "Today was the big push from Winslow to Santa Fe—the kind of drive where your playlist starts strong, then gets weird, then somehow circles back to confidence.",
      "We made a nostalgia detour at the Wigwam Motel in Holbrook, because if Route 66 offers you giant teepee rooms and retro roadside chaos, you say yes and ask questions never.",
      "Later, somewhere in “please let this gas gauge be lying” territory, Maverik (Gallup) came through like a roadside guardian angel with snacks, fuel, and the exact energy of “you're not stranded yet.”",
      "Before we officially called it a Santa Fe arrival, we stopped at Dairy Queen at the Casa Blanca gas station—my first time ever trying it. The employee did the legendary upside-down ice cream move like it was a magic trick, and honestly, I was way too impressed for a grown adult.",
      "Then we checked into Hotel Santa Fe, and it's seriously cozy. After a long haul day, this place felt like a reward, and we're staying here for two nights to reset before the next stretch.",
    ],
    stops: ["Winslow", "Wigwam Motel", "Maverik Gallup", "Dairy Queen Casa Blanca", "Hotel Santa Fe"],
  },
  {
    part: 1,
    day: 7,
    slug: "standing-around-winslow",
    title: "Flagstaff to Winslow, Corner Stop, and La Posada",
    date: "2026-02-18",
    dateDisplay: "Feb 18, 2026",
    location: "Winslow",
    weather: "Clear, 8.4/-3.2°C.",
    summary: "Short drive from Flagstaff to Winslow with a stop at Standin' on the Corner Park and an afternoon at La Posada Hotel and museum.",
    image: "/assets/part1/day7-winslow-la-posada.webp",
    imageAlt: "Pixel-art Winslow street corner and La Posada Hotel beneath a clear Arizona sky",
    imageCaption: "WINSLOW · STANDIN' ON THE CORNER",
    body: [
      "Today was a short hop from Flagstaff to Winslow—a nice break from the longer driving days and a chance to pretend we are “taking it easy” while still doing a full itinerary like absolute professionals.",
      "First stop in town was Standin' on the Corner Park. Classic Winslow energy. We did the mandatory gawking, photo ops, and “yes, this song is now permanently stuck in my head” moment.",
      "After that, we headed to La Posada Hotel—which is genuinely beautiful. Historic, full of character, and one of those places where every hallway makes you slow down and look around. We also spent time in the Affeldt Mion Museum there, which made the whole stop feel less like “quick overnight” and more like a proper destination.",
      "Short drive day, high vibes day, zero regrets day.",
    ],
    stops: ["Flagstaff", "Standin' on the Corner Park", "La Posada Hotel", "Affeldt Mion Museum"],
  },
  {
    part: 1,
    day: 6,
    slug: "snowy-white-knuckle-driving-frozen-flagstaff-wander",
    title: "Snowy White-Knuckle Driving and a Frozen Flagstaff Wander",
    date: "2026-02-17",
    dateDisplay: "Feb 17, 2026",
    location: "Flagstaff",
    weather: "Heavy snowfall, -1.2/-8.2°C.",
    summary: "Williams to Flagstaff in steady snow, a cold wander, and a warm meal at Little America.",
    image: "/assets/part1/day6-snowy-flagstaff.webp",
    imageAlt: "Pixel-art road-trip sedan driving through heavy snow toward Flagstaff's warm downtown lights",
    imageCaption: "WILLIAMS → FLAGSTAFF · WINTER ROAD",
    body: [
      "We drove from Williams to Flagstaff today and the weather decided to add a little drama: steady snow, gray skies, and the kind of road conditions that make you grip the wheel like it owes you money. I‑40 was slow but manageable—mostly a cautious parade of semis and SUVs—so we took it easy, watched for slick patches on bridges and overpasses, and enjoyed the surprisingly pretty snow-dusted pines once the nerves dialed down.",
      "Rolled into Flagstaff cold, relieved, and immediately in search of heat. And then (because we're apparently allergic to staying warm) we went over to the Riordan Mansion and did a wander through Heritage Square—with my hands absolutely freezing the entire time. 10/10 scenic winter vibes, 0/10 finger circulation.",
      "We capped it off by buying two pizzas for “afternoon tea,” which feels extremely correct in this climate: classy in spirit, feral in execution.",
      "And then we ended the day with a great meal inside Little America—warm, cozy, and exactly what our frozen souls needed.",
    ],
    stops: ["Williams", "Interstate 40", "Riordan Mansion", "Heritage Square", "Little America Flagstaff"],
  },
  {
    part: 1,
    day: 5,
    slug: "side-quests-seligman-kitsch-williams-deep-freeze",
    title: "Side Quests, Seligman Kitsch, and the Williams Deep Freeze",
    date: "2026-02-16",
    dateDisplay: "Feb 16, 2026",
    location: "Williams",
    weather: "Heavy snowfall, 2.3/-3.2°C.",
    summary: "Kingman museums + Bonelli House, then Hackberry, a stop at the old Truxton Canyon school site, Seligman kitsch, and on to Williams.",
    image: "/assets/part1/day5-kingman-williams.webp",
    imageAlt: "Pixel-art Route 66 roadside store and Seligman landmarks on the climb from Kingman to snowy Williams",
    imageCaption: "KINGMAN → WILLIAMS · ROADSIDE DETOURS",
    body: [
      "Started the morning in Kingman with a shockingly good Best Western breakfast (I know). Actual hot food, decent coffee, and waffles that didn't taste like foam packaging.",
      "Then we did the museum double-feature: the Route 66 Museum and the Mohave Museum—followed by a quick peek at the Bonelli House for some “people actually lived like this” energy.",
      "After that we rolled out to the Hackberry General Store, which is equal parts roadside shrine, gift shop, and nostalgia trap (in a good way).",
      "We made a quick stop at the old Truxton Canyon Training School site (Valentine's weirdly fascinating “how is this still here?” time capsule), then kept rolling.",
      "After that, we rolled through Seligman for a quick dose of classic Route 66 kitsch and then pointed the car toward Williams for the day (where the elevation politely reminds you that Arizona can, in fact, be cold).",
    ],
    stops: ["Best Western Kingman", "Arizona Route 66 Museum", "Mohave Museum", "Bonelli House", "Hackberry General Store", "Truxton Canyon Training School", "Seligman", "Williams"],
  },
  {
    part: 1,
    day: 4,
    slug: "oatman-donkey-parade-road-to-kingman",
    title: "Donkey Traffic Control in Oatman (and the Road to Kingman)",
    date: "2026-02-15",
    dateDisplay: "Feb 15, 2026",
    location: "Kingman",
    weather: "Moderate rain, 16.6/8.1°C.",
    summary: "Welcome to California sign, Oatman donkey chaos, then overnight in Kingman (and Mr D'z).",
    image: "/assets/part1/day4-oatman-kingman.webp",
    imageAlt: "Pixel-art wild burros blocking Oatman's rainy main street on the road to Kingman",
    imageCaption: "OATMAN · DONKEY TRAFFIC",
    body: [
      "Before Oatman, we pulled over at the Welcome to California Sign for a quick photo—because road trips are 40% driving and 60% proving you were there.",
      "Then we made it into Oatman, walked the old wooden sidewalks, and soaked in the full old-west vibe.",
      "The headline event was the donkey situation: donkeys everywhere, confidently occupying the road like local government officials.",
      "By evening we reached Kingman, checked in, and had dinner at Mr D'z Diner. We asked for a to-go box for our salad… and then completely forgot to take it. We even drove back for it, but the waitress had already tossed it—RIP salad, you were too pure for this journey. Sadly, both the burger and the steak were pretty underwhelming, so we called it early and let the donkeys keep running traffic operations without us.",
    ],
    stops: ["Welcome to California Sign", "Oatman", "Kingman", "Mr D'z Route 66 Diner"],
  },
  {
    part: 1,
    day: 3,
    slug: "bottle-trees-ghost-towns-neon-needles",
    title: "Bottle Trees, Ghost Towns, Neon Lights, and Needles",
    date: "2026-02-14",
    dateDisplay: "Feb 14, 2026",
    location: "Needles",
    weather: "Overcast, 24.1/13.9°C.",
    summary: "Museums in Barstow, then bottle trees, Calico, Bagdad Cafe, Roy's neon, and a one-night stop in Needles (plus River City Pizza).",
    image: "/assets/part1/day3-bottle-trees-needles.webp",
    imageAlt: "Pixel-art bottle trees, ghost-town buildings, and desert neon along Route 66 toward Needles",
    imageCaption: "HIGH DESERT · NEON & GHOST TOWNS",
    body: [
      "Day 3 was pure High Desert chaos in the best way: lots of stops, zero restraint.",
      "We kicked off in Barstow at the Mother Road Museum, then hit the Harvey House like responsible travelers who absolutely have a schedule and definitely stick to it.",
      "Next was Elmer's Bottle Tree Ranch in Oro Grande, where someone looked at a pile of bottles and said, “Yes, this is art,” and honestly, they were right.",
      "We rolled through Calico Ghost Town, stopped at Bagdad Cafe, and grabbed the classic photo at the Roy's Motel neon sign.",
      "By evening we reached Needles for the night. Gas on this stretch was slow and expensive, which was a fun little reminder that suffering builds character.",
      "We closed out with pizza at River City Pizza in Needles and called it a win.",
    ],
    stops: ["Barstow Mother Road Museum", "Harvey House", "Elmer's Bottle Tree Ranch", "Calico Ghost Town", "Bagdad Cafe", "Roy's Motel", "Needles", "River City Pizza"],
  },
  {
    part: 1,
    day: 2,
    slug: "pier-selfies-end-of-trail-barstow",
    title: "Pier Selfies, End-of-the-Trail Photos, and a Barstow Reality Check",
    date: "2026-02-13",
    dateDisplay: "Feb 13, 2026",
    location: "Barstow",
    weather: "Overcast, 20.2/4.4°C.",
    summary: "Santa Monica Pier, Pasadena smoothies, the End of the Trail sign, the original McDonald's museum, a Victorville museum stop, then rolling into Barstow.",
    image: "/assets/part1/day2-santa-monica-barstow.webp",
    imageAlt: "Pixel-art Santa Monica Pier and a Route 66 road-trip sedan heading inland toward Barstow",
    imageCaption: "SANTA MONICA · ROUTE 66 BEGINS",
    body: [
      "Day 2 finally looked like a real Route 66 day instead of an airport side quest.",
      "We started at Santa Monica Pier and got the mandatory End of the Trail Sign photo, because if there isn't photographic evidence, did the trip even happen?",
      "Then it was off to Pasadena for smoothies, followed by a stop at the Original McDonald's Museum—a historic site proving that road-trip nutrition has always been a flexible concept.",
      "We made a quick museum stop at the Route 66 Museum (Victorville), then tried Raising Cane's Chicken Fingers for the first time in the name of science.",
      "By night we rolled into Barstow, tired, overfed, and extremely confident in our ability to turn every stop into a full production.",
    ],
    stops: ["Santa Monica Pier", "End of the Trail Sign", "Pasadena", "Original McDonald's Museum", "California Route 66 Museum", "Barstow"],
  },
  {
    part: 1,
    day: 1,
    slug: "tsa-glamour-airport-limbo-mcnuggets",
    title: "TSA Glamour, Airport Limbo, and McNuggets",
    date: "2026-02-12",
    dateDisplay: "Feb 12, 2026",
    location: "Los Angeles",
    weather: "Overcast, 20.4/6.2°C.",
    summary: "Flew SJC to LAX, checked into Jamaica Bay Inn, and celebrated elite travel culture with McDonald's for dinner.",
    image: "/assets/part1/day1-sjc-lax.webp",
    imageAlt: "Pixel-art airport terminal overlooking a plane and the rainy Marina del Rey waterfront",
    imageCaption: "CALIFORNIA · AIRPORT LAUNCH",
    body: [
      "Day 1 of our legendary Route 66 road trip began with the bold, authentic road-warrior move of… flying from SJC to LAX.",
      "Nothing says “classic highway adventure” like TSA, gate changes, and paying airport prices for water like it's a collectible item.",
      "After landing at LAX, we checked into Jamaica Bay Inn and pretended this was all part of a highly strategic launch sequence.",
      "Dinner was McDonald's, because after navigating airport logistics, the Michelin guide can wait and fries cannot.",
      "Tomorrow: actual miles on Route 66, fewer boarding announcements, and hopefully less emotional damage from carry-on roulette.",
    ],
    stops: ["San Jose International Airport", "Los Angeles International Airport", "Jamaica Bay Inn"],
  },
];

export const getEntriesForPart = (part) => entries.filter((entry) => entry.part === part);

export const getEntryBySlug = (slug) => entries.find((entry) => entry.slug === slug);
