export const chapters = {
  2: {
    id: 2,
    label: "PART II",
    route: "CHICAGO → ALBUQUERQUE",
    dates: "Aug 21–31, 2026",
    intro: "The road continues west.",
    hero: "/assets/part2/route66-part2-hero.png",
    heroAlt: "Pixel-art rental car heading west on Route 66 across the Illinois prairie",
  },
  1: {
    id: 1,
    label: "PART I",
    route: "SANTA MONICA → ALBUQUERQUE",
    dates: "Feb 12–21, 2026",
    intro: "The first saved game: California to New Mexico.",
    hero: "/assets/part1/route66-part1-hero.png",
    heroAlt: "Pixel-art Route 66 journey from the Pacific coast toward the New Mexico desert",
  },
};

export const entries = [
  {
    part: 2,
    day: 11,
    slug: "spaceships-neon-old-town",
    title: "Spaceships, Neon & Old Town",
    date: "2026-08-31",
    dateDisplay: "Aug 31, 2026",
    location: "Albuquerque, New Mexico",
    weather: "Broken clouds, 30/21°C.",
    summary: "Albuquerque's finale moved from a neighborhood spaceship to Route 66 neon in Nob Hill, a light Flying Star lunch, Old Town Plaza, and San Felipe de Neri Church.",
    image: "/assets/part2/day11-spaceships-neon-old-town.webp",
    imageAlt: "Pixel-art Albuquerque Route 66 scene with the Futuro-style Spaceship House, Flying Star Cafe neon, Old Town adobe buildings, San Felipe de Neri Church, and a cream road-trip sedan",
    imageCaption: "TUCUMCARI → ALBUQUERQUE · SPACESHIPS, NEON & OLD TOWN",
    body: [
      "Albuquerque opened with a white UFO apparently parked beside an otherwise normal neighborhood. The Futuro-style Spaceship House turned a quick exterior stop into an immediate architecture mystery, especially the clear blue-tinted column beneath the pod: it looked water-filled, which was enough to begin the investigation before we had even moved on.",
      "Nob Hill put the day's biggest Route 66 surprise directly under our tires. Central Avenue here is the historic highway itself, so what looked like a modern lunch neighborhood was still part of the Mother Road. The surviving neon and mid-century streetscape made the old route feel active rather than sealed behind museum glass.",
      "Flying Star Cafe handled the light-lunch mission and one last menu debate. Turkey Jack, shrimp tacos, and something cold all entered the conversation, while the cafe's neon and Central Avenue address confirmed that lunch had not actually taken us off Route 66.",
      "Old Town Plaza changed Albuquerque's visual language from neon and mid-century storefronts to shade trees, adobe walls, and a traditional central square. After ten days of roadside giants, motor courts, museums, and painted signs, the slower plaza felt like the road trip had finally reached its closing scene.",
      "San Felipe de Neri Church became the final sightseeing stop. Its white towers rose directly beside Old Town Plaza, and the quiet church visit supplied a calm ending before airport mode took over. Route 66 had started for us in Chicago beneath city lights; eleven days later, it ended here among adobe walls in Albuquerque.",
    ],
    stops: ["Spaceship House · Futuro exterior", "Nob Hill · Central Avenue Route 66", "Flying Star Cafe", "Old Town Plaza", "San Felipe de Neri Church"],
  },
  {
    part: 2,
    day: 10,
    slug: "pie-painted-lines-neon-camels",
    title: "Pie, Painted Lines & Neon Camels",
    date: "2026-08-30",
    dateDisplay: "Aug 30, 2026",
    location: "Tucumcari, New Mexico",
    weather: "Hot and mostly sunny, 37/20°C.",
    summary: "A castle-like Amarillo landmark led to pie and a midpoint audit in Adrian, then Tucumcari turned sunset into a long parade of murals, neon, camels, curios, and wonderfully weathered signs.",
    image: "/assets/part2/day10-pie-painted-lines-neon-camels.webp",
    imageAlt: "Pixel-art sunset Route 66 scene with The Nat, Midpoint Cafe and a slice of pie, the Route 66 midpoint marker, the Welcome to Tucumcari mural, Motel Safari's camel sign, Tee Pee Curios, the Tucumcari Inn sign, and a cream road-trip sedan",
    imageCaption: "AMARILLO → ADRIAN → TUCUMCARI · PIE, PAINTED LINES & NEON CAMELS",
    body: [
      "Historic Sixth Street supplied one last Amarillo mystery before the drive west: The Nat, a fortress-like building with battlements, an arched entrance, and a name that made no sense until its first life came back into view. It opened in 1922 as the Amarillo Natatorium, an open-air swimming pool; the pool was later covered by a maple dance floor, and the castle façade belonged to its era as The Nat Dine and Dance Palace. The building looked like a Fallout stronghold, but its real backstory was somehow even stranger.",
      "At Midpoint Cafe in Adrian, pie won. The homemade desserts became known as Ugly Crust Pies because their baker thought her crusts never looked as beautiful as her grandmother's, not because anything was wrong with the taste. Outside, the 1,139-miles-each-way sign and painted Route 66 line triggered a full GIS audit of whether this is the mathematically exact midpoint. The honest answer depends on which historic alignment and endpoints are measured, but the photographed line opposite the cafe still does its real job perfectly: it makes everybody stop halfway and take the picture.",
      "The Welcome to Tucumcari mural turned one wall into a left-to-right history lesson. Its railroad, schoolhouse, cowboy, Native figure, wildlife, oil derricks, wind turbines, and old car led straight into questions about the Rock Island railroad construction camp that began as Ragtown, acquired the gloriously lawless nickname Six Shooter Siding, and grew into Tucumcari. One photograph managed to contain the town's origin story and most of its visual vocabulary.",
      "La Cita announced itself with a huge rooftop sombrero and a proudly old-fashioned MEXICAN FOOD sign. We photographed the exterior rather than pretending a sign proved we ate there; it was one bright roadside landmark in a town where the signs are often as memorable as the businesses beneath them.",
      "Motel Safari's camel-and-rider sign was already excellent, and then the neon added an audible bzzzzz to the experience. Learning that the 1959 motel was built in the angular mid-century style now called Googie or Doo Wop explained the geometry, while the camel and a vintage 'more doctors smoke Camels' advertisement opened a completely different rabbit hole: an ad campaign that would be boycotted instantly today. Tucumcari had turned one motel sign into architecture, advertising history, and comedy at the same time.",
      "Blue Swallow Motel made the old road's geography wonderfully literal: yes, the street running directly past its rooms and famous neon is the former Route 66 alignment. The little motor court looked less like a preserved museum object than a place where the highway's motel era had simply refused to log off.",
      "Tee Pee Curios looked exactly like a Fallout merchant location after dark: glowing storefront, giant teepee shapes, geometric patterns, and enough roadside treasure to start thinking in caps. The obvious plan was to enter and trade; the less comforting thought was that our barter skill points might be too low and every souvenir deal would become a financial debuff.",
      "Golden Dragon supplied the California cultural-comparison stop. Its GOLDEN DRAGON CHINESE RESTAURANT sign immediately produced the theory that a Bay Area restaurant called 金龍 would somehow have mostly white customers inside. Tucumcari Route 66 was still generating sociology jokes between motel signs.",
      "Del's Restaurant appeared at sunset beneath a cow perched on its roadside sign and the reassuring words SINCE 1956. We stopped at the sign rather than converting a dinner discussion into a meal we did not confirm; the cow alone earned its place in the roadside-animal collection.",
      "Tucumcari Inn closed the loop with a weathered blue-and-tan sign, palm graphics, a $29.9 rate, WIFI, and marquee letters that looked as if somebody had rearranged them during the apocalypse. Against the evening sky, it captured the strange balance of Tucumcari perfectly: part living neon museum, part faded motor court, and part Route 66 ghost level that still lets you drive straight through the set.",
    ],
    stops: ["Historic Sixth Street · The Nat", "Route 66 Midpoint · Midpoint Cafe", "Welcome to Tucumcari mural", "La Cita Mexican Restaurant · roadside sign", "Motel Safari · camel neon", "Blue Swallow Motel", "Tee Pee Curios", "Golden Dragon Chinese Restaurant", "Del's Restaurant · cow sign", "Tucumcari Inn · vintage sign"],
  },
  {
    part: 2,
    day: 9,
    slug: "museum-mclean-big-texan",
    title: "Museum Mysteries & Texas-Sized Dinner",
    date: "2026-08-29",
    dateDisplay: "Aug 29, 2026",
    location: "Amarillo, Texas",
    weather: "Hot and windy, 38/21°C.",
    summary: "A westbound day through Clinton's highway time capsule, McLean's cottage-sized Phillips 66 station, the windy Texas Panhandle, and The Big Texan's wonderfully excessive finale.",
    image: "/assets/part2/day9-clinton-mclean-big-texan.webp",
    imageAlt: "Pixel-art Route 66 scene with the Oklahoma Route 66 Museum, McLean's cottage-style Phillips 66 station, the open Texas Panhandle, The Big Texan and its green dinosaur, and a cream road-trip sedan",
    imageCaption: "OKLAHOMA CITY → AMARILLO · MUSEUM MYSTERIES & TEXAS-SIZED DINNER",
    body: [
      "The Oklahoma Route 66 Museum in Clinton turned into a long chain of ‘what is that?’ discoveries. A smudge pot burned heavy oil to protect orchards from frost; an old visible-cylinder gas pump used gravity after measuring the fuel overhead; and lead once appeared everywhere from gasoline to paint with consequences nobody should miss. The exhibits kept going through FSA-era food, Pop Hicks, Valentine diners, Beverly Chicken's deliberately confusing franchise pitch, soda jerks, hitchhiking signs, Lee Way trucks, RC Cola, jukebox bubble tubes, railroad machinery, and Will Rogers Highway history. It felt less like one museum stop than an entire century of roadside questions packed into one building.",
      "McLean's little Phillips 66 station was the opposite kind of history lesson: one tiny Tudor Revival gas station standing quietly beside the old road. Built to resemble a cottage, complete with a steep gable and chimney, it served motorists for decades before preservationists restored it. After Clinton's rooms full of highway artifacts, seeing a real early filling station still sitting where travelers once pulled in made the story feel suddenly physical.",
      "Crossing into the Texas Panhandle changed the whole visual scale. The High Plains were flat, open, bright, and windy enough to explain the enormous sky—and the road filled with tall pickups, brush guards, cowboy hats, Wrangler jeans, oversized belt buckles, and unapologetically obvious Texas style. Even the map joined the joke: the Panhandle really does look like somebody attached a handle to the top of Texas.",
      "The Big Texan Steak Ranch finished the day at maximum Amarillo volume. The place is famous for the 72-ounce steak challenge—finish the full meal in one hour and it is free—but the giant green dinosaur outside, Big Tex Rex, was already enough roadside spectacle before dinner. Between the Old West décor, mountain-oyster questions, decorated dinosaur pins, and a restaurant built around public competitive eating, Texas had managed to turn supper into one more Route 66 attraction.",
    ],
    stops: ["Oklahoma Route 66 Museum · Clinton", "McLean Phillips 66 station", "Texas Panhandle · High Plains", "The Big Texan Steak Ranch · Amarillo"],
  },
  {
    part: 2,
    day: 8,
    slug: "totems-whales-round-barns-bank-vaults",
    title: "Totems, Whales, Round Barns & Bank Vaults",
    date: "2026-08-28",
    dateDisplay: "Aug 28, 2026",
    location: "Oklahoma City, Oklahoma",
    weather: "Hot and mostly sunny, 37/23°C.",
    summary: "An Oklahoma day of concrete folk art, a smiling swimming-hole whale, a round barn bent from green oak, one aggressively weird soda, and a hotel hiding a bank vault.",
    image: "/assets/part2/day8-oklahoma-route66.webp",
    imageAlt: "Pixel-art Oklahoma Route 66 montage with Ed Galloway's Totem Pole, the Blue Whale of Catoosa, Arcadia Round Barn, the POPS bottle sculpture, The National hotel, and a cream road-trip sedan",
    imageCaption: "JOPLIN → OKLAHOMA CITY · TOTEMS, WHALES & VAULTS",
    body: [
      "Ed Galloway's Totem Pole Park was the first proper Oklahoma side quest. The enormous concrete folk-art tower is called the world's largest concrete totem pole, although its painted faces and creatures came from one artist's imagination rather than a Native ceremonial tradition. The nearby Fiddle House Museum added Galloway's carved fiddles and more handmade oddities—including one figure that looked enough like a hip-hop alien to become the day's first unofficial mascot.",
      "The Blue Whale of Catoosa was even stranger in person: a smiling blue animal stretched across a quiet pond with old diving platforms still attached. It made much more sense after learning that this really was once a swimming-hole attraction where families climbed, jumped, and slid into the water. The whale no longer shoots water or welcomes swimmers, but it still looks permanently delighted to see every car that pulls in.",
      "Arcadia Round Barn turned a red roadside landmark into an engineering lesson. Its builders soaked green bur-oak boards until they could bend around the circular frame, creating curved walls and a broad loft under a domed roof. What first looked like Victorian-era whimsy was also practical Oklahoma carpentry—and a building that survived long enough for volunteers to rescue it from collapse.",
      "POPS was the day's fluorescent soda laboratory. The giant bottle sculpture outside led to shelves packed with bottles inside, where the mission quickly changed from finding something refreshing to locating bacon or the weirdest possible flavor. One novelty soda eventually earned the immediate review, ‘Damn, that's the weirdest thing I've ever had,’ which is probably the highest honor available at a Route 66 soda ranch.",
      "The National made the overnight stop feel like one more attraction. Inside Oklahoma City's restored First National Center, the old banking details kept opening new paths: historic lobby murals, enormous vault doors, the bottle-lined Library of Distilled Spirits, and even an entrance into the downtown pedestrian tunnel system. Following directions past the cowboy shop and IBC Bank to find a real bank vault inside our hotel was a suitably ridiculous way to end the day.",
    ],
    stops: ["Totem Pole Park · Fiddle House Museum", "Blue Whale of Catoosa", "Arcadia Round Barn", "POPS 66", "The National · First National Center"],
  },
  {
    part: 2,
    day: 7,
    slug: "chubby-angels-red-oak-beige-dinner",
    title: "Chubby Angels, Red Oak & Beige Dinner",
    date: "2026-08-27",
    dateDisplay: "Aug 27, 2026",
    location: "Joplin, Missouri",
    weather: "Sunny and hot, 34/17°C.",
    summary: "A southwest Missouri day of roadside farm oddities, Precious Moments angels, Red Oak II's rescued town, antique gas-pump engineering, fresh Walmart prints, and a statistically optimized hotel dinner.",
    image: "/assets/part2/day7-precious-moments-red-oak-corrected.webp",
    imageAlt: "Pixel-art southwest Missouri Route 66 montage with rustic farm cues, a white chapel, Red Oak II buildings, a vintage gas pump, an old trolley, and a cream road-trip sedan",
    imageCaption: "SPRINGFIELD → JOPLIN · ANGELS, RED OAK & ROAD ART",
    body: [
      "Day 7 left the Route 66 Rail Haven and followed the old road west past roadside names like FoxFire Farm and Cackleberry Park to Precious Moments Chapel in Carthage. Sam Butcher's teardrop-eyed children began on Jonathan & David greeting cards, found a huge audience through Hallmark, and expanded into figurines and the chapel. Inside, the enormous Hallelujah Square mural presented his personal vision of heaven through extremely chubby angels, prompting difficult questions but also the conclusion that a place can feel strange to us and still deserve a respectful, curious look.",
      "Red Oak II was the day's hard anchor. Lowell Davis rescued buildings from his declining hometown and rebuilt them near Carthage as a living art village, so our fear of trespassing made sense: it is part ghost town, part outdoor museum, and part real neighborhood. In one long wander we found the green Belle Starr house, Jesse James stories, a Birney streetcar, the ‘Alter Ego,’ ‘Paintings Don't Lie,’ and ‘Crap Duster’ airplane, and visible-cylinder gasoline pumps that attendants filled by hand before gravity carried the measured fuel into a car. At the visitor center, Lowell's wife confirmed that the gift shop sells his work as giclée prints—high-quality reproductions of the memories he rebuilt here.",
      "Joplin supplied the practical epilogue. The Walmart photo order was ready and the prints came out genuinely nice, then the Drury Inn 5:30 Kickback became a beige-food prioritization problem serious enough to justify a Monte Carlo simulation. After a day of angels, rescued buildings, and gravity-fed gasoline, statistics choosing dinner somehow felt perfectly normal.",
    ],
    stops: ["Springfield → Carthage · Precious Moments Chapel", "Red Oak II · rescued town, streetcar & vintage pumps", "Joplin · Walmart Photo · Drury Inn & Suites"],
  },
  {
    part: 2,
    day: 6,
    slug: "cuba-murals-rocker-beaver-nuggets",
    title: "Murals, Rockers & Beaver Nuggets",
    date: "2026-08-26",
    dateDisplay: "Aug 26, 2026",
    location: "Springfield, Missouri",
    weather: "Hot and humid, 36/22°C.",
    summary: "A humid Missouri run past a giant caveman advertisement to Cuba's mural streets, an enormous rocker, Munger Moss neon, Buc-ee's, and a real Route 66 motor-court finish.",
    image: "/assets/part2/day6-st-louis-springfield-mo-corrected.webp",
    imageAlt: "Pixel-art Missouri Route 66 montage with Cuba murals, the Route 66 Rocker, Munger Moss Motel, a large travel center, Rail Haven, and a cream road-trip sedan",
    imageCaption: "ST. LOUIS → SPRINGFIELD · MURALS, ROCKERS & MOTOR COURTS",
    body: [
      "Day 6 traded St. Louis monuments for the Ozarks—and immediately explained why 90°F in Missouri feels nothing like 90°F in the Bay Area. The temperature was only part of the problem; the dew point was doing the real sweating on our behalf. A giant caveman advertisement for Meramec Caverns became a roadside mystery as we kept moving west.",
      "Cuba turned Route 66 into an outdoor gallery. The Walldogs murals cover local history across downtown walls, and the town name came from nineteenth-century American sympathy for Cuba—not because a pocket of Missouri somehow became Caribbean. Every block answered one question and created three more.",
      "At Fanning 66 Outpost, the Route 66 Rocker proved that a chair can stop traffic if it is large enough. It was once certified as the world's largest rocking chair; now it is a very tall roadside landmark that has been politely prevented from actually rocking.",
      "Munger Moss Motel brought back the classic road with its neon, motor-court history, and a ‘You Are Here!’ signpost pointing in every direction. One sign managed to turn a quiet motel stop into a complete geography lesson.",
      "Springfield's new Buc-ee's became dinner and souvenir headquarters. A three-meat sandwich and candied cashews sounded reasonable; Beaver Nuggets made less semantic sense but much more road-trip sense. The tiny plush beaver mission failed because the shelf had already entered Halloween mode.",
      "We ended at the Best Western Route 66 Rail Haven, a genuine 1938 motor court with the rooms arranged around the car the way Route 66 intended. After murals, neon, Beaver Nuggets, and one enormous rocking chair, tomorrow's hard anchor is Red Oak II before sunset.",
    ],
    stops: ["St. Louis → the Ozarks · Meramec roadside sign", "Cuba mural district", "Fanning 66 Outpost · Route 66 Rocker", "Munger Moss Motel", "Buc-ee's Springfield", "Best Western Route 66 Rail Haven"],
  },
  {
    part: 2,
    day: 5,
    slug: "arch-trams-bridge-bends-frozen-custard",
    title: "Arch Trams, Bridge Bends & Frozen Custard",
    date: "2026-08-25",
    dateDisplay: "Aug 25, 2026",
    location: "St. Louis, Missouri",
    weather: "Partly cloudy, 31/19°C.",
    summary: "A full St. Louis day with the Gateway Arch, a surprise tram ride, City Museum, Snarf's, Route 66's crooked Mississippi crossing, giant ketchup, frozen custard, and Union Station after dark.",
    image: "/assets/part2/day5-st-louis-route66.webp",
    imageAlt: "Pixel-art St. Louis Route 66 montage with the Gateway Arch, City Museum, Chain of Rocks Bridge, giant Catsup Bottle, Ted Drewes, Union Station, and a cream road-trip sedan",
    imageCaption: "ST. LOUIS · GATEWAY, BRIDGE & CUSTARD",
    body: [
      "Day 5 began under the Gateway Arch, where the museum connected Mound City, the Battle of Fort San Carlos, the Louisiana Purchase, westward expansion, and St. Louis's claim to be the Gateway to the West. The original plan was museum and grounds only, but the Arch won: with only the south tram running, we folded into its tiny retro capsule and rode to the top. The little windows made more sense once we remembered that every opening had to fit inside a 630-foot stainless-steel curve—still a very ambitious amount of engineering for such a narrow view slot.",
      "City Museum got its two-hour highlights window next. Calling it a museum feels wildly insufficient; it is more like an old shoe factory that swallowed an art project, a playground, and every interesting piece of industrial scrap in Missouri. It was the day's least Route 66 stop and somehow one of its most perfectly roadside-American stops.",
      "Lunch at Snarf's inside the MX brought a German Dog and a Super Club for three people. We also learned that to snarf a sandwich means to inhale it at cartoon speed, which was useful vocabulary after a morning of museum mileage. Outside, downtown felt strangely quiet enough to start the next investigation: how can a city center full of major companies still feel like a ghost town on foot?",
      "Late afternoon put us back on old Route 66 at the Chain of Rocks Bridge. We walked onto the retired automobile crossing, found the famous bend hanging over the Mississippi, looked out toward the water-intake towers, and met the recreated 66 Auto Court vacancy sign—the remains of a motor-court world that once waited for drivers on the St. Louis approach.",
      "The World's Largest Catsup Bottle followed, except the giant bottle is technically a 170-foot water tower wearing ketchup-bottle clothing. Then Ted Drewes on Chippewa supplied the essential frozen-custard ending: thick enough to earn the name concrete and exactly the kind of institution that makes a Route 66 detour feel mandatory.",
      "We still had enough energy for St. Louis Union Station after dark. First we found the enormous train shed and its Midway—meaning carnival games, not the halfway point—then went hunting for the actual hotel lobby and Grand Hall. The light show refused to appear on command, but the station's half-open roof, old railway scale, aquarium-era attractions, and giant arcade made the whole place feel like a historic terminal had unlocked a very strange bonus level.",
    ],
    stops: ["Gateway Arch Museum · Tram to the Top", "City Museum", "Snarf's Sandwiches · Downtown MX", "Chain of Rocks Bridge · 66 Auto Court", "World's Largest Catsup Bottle · Ted Drewes", "St. Louis Union Station · Midway · Grand Hall"],
  },
  {
    part: 2,
    day: 4,
    slug: "lincoln-miles-of-memories-cozy-dog-st-louis",
    title: "Lincoln, Miles of Memories & St. Louis",
    date: "2026-08-24",
    dateDisplay: "Aug 24, 2026",
    location: "St. Louis, Missouri",
    weather: "Sunny, 29/16°C.",
    summary: "A final Lincoln morning, an enormous Route 66 centennial exhibition, the original Cozy Dog story, one flag-holding roadside giant, and a late-afternoon run into St. Louis.",
    image: "/assets/part2/day4-springfield-st-louis.webp",
    imageAlt: "Pixel-art cream road-trip sedan passing Springfield landmarks and Cozy Dog on Route 66 toward the St. Louis Gateway Arch",
    imageCaption: "SPRINGFIELD → ST. LOUIS · A CENTURY OF ROAD",
    body: [
      "Day 4 began with the Lincoln stop we could not squeeze into yesterday. Lincoln Home made the president feel less like a monument and more like a real Springfield neighbor—with a busy household, troublesome children, and a life waiting just beyond the front door.",
      "Then the Illinois State Museum's Miles of Memories exhibition turned out to be huge. Colored Depression glass, cinder goggles, a Nash Tower of Value, a Crosley Hotshot, coffee makers, phonograph cylinders, and enough Route 66 artifacts to make a century of roadside history feel like one extremely crowded family attic.",
      "Cozy Dog Drive-In brought us back to the essential road-trip questions: how to order, whether this counts as the invention of the corn dog, and why food on a stick tastes more historically important beside Route 66. We also paid our respects to Springfield's flag-holding Lauterbach Giant.",
      "By late afternoon the cream sedan was pointed south toward St. Louis. The Gateway Arch appeared ahead like the next level's title screen, and we checked into the Hampton Inn downtown—close enough to the riverfront to start asking how a 1965 monument became the symbol of westward expansion before we had even unpacked.",
    ],
    stops: ["Lincoln Home", "Illinois State Museum · Miles of Memories", "Cozy Dog Drive-In · Lauterbach Giant", "Route 66 to St. Louis · Hampton Inn St. Louis-Downtown"],
  },
  {
    part: 2,
    day: 3,
    slug: "pontiac-murals-lincolns-springfield",
    title: "Murals, Museums & Lincoln's Springfield",
    date: "2026-08-23",
    dateDisplay: "Aug 23, 2026",
    location: "Springfield, Illinois",
    weather: "Sunny, 27/14°C.",
    summary: "Pontiac museums and murals, a bridge that moves under your feet, a hot-dog-holding giant, and a Springfield arrival too late for Lincoln Home and the Kickback.",
    image: "/assets/part2/day3-pontiac-springfield.png",
    imageAlt: "Pixel-art Pontiac mural and swinging bridge leading toward Springfield's capitol dome",
    imageCaption: "PONTIAC · ROAD-DAY MORNING",
    body: [
      "Day 3 began with a glamorous rental-car subplot: a low tire. We added air, watched the number like responsible adults, and unlocked a new Route 66 achievement—roadside maintenance before breakfast.",
      "Pontiac was worth the pause. We worked through the Route 66 Hall of Fame Museum and the Pontiac-Oakland Museum, then followed the Walldogs murals around downtown like a scavenger hunt designed by people with very strong feelings about brick walls.",
      "The so-called Swinging Bridge turned out not to swing open at all. It is a narrow suspension footbridge, and the deck moves just enough under your feet to make the crossing feel more adventurous than the map suggested.",
      "After a Wally's stop for the full wall-of-jerky and popcorn-flavor experience, we met Atlanta's Paul Bunyan holding his giant hot dog and continued toward Springfield. Closing time won the race, turning Lincoln Home into tomorrow morning's first mission.",
      "We checked into Drury Inn & Suites Springfield and learned the cruelest hotel lesson of the trip: the 5:30 Kickback does not wait for anyone. At least we were finally in Lincoln—and Cozy Dog—territory, with the unfinished stops lined up for Day 4.",
    ],
    stops: ["Rental car · low-tire morning", "Pontiac museums · Walldogs murals", "Pontiac Swinging Bridge", "Wally's Pontiac · Atlanta Paul Bunyan", "Drury Inn & Suites Springfield"],
  },
  {
    part: 2,
    day: 2,
    slug: "lou-mitchells-joliet-gemini-giant",
    title: "Lou Mitchell's, Joliet & the Gemini Giant",
    date: "2026-08-22",
    dateDisplay: "Aug 22, 2026",
    location: "Pontiac, Illinois",
    weather: "Partly cloudy, 27/16°C.",
    summary: "A dawn landing at O'Hare, classic diner fuel, Chicago and Joliet detours, the Gemini Giant, and the first real stretch of the Mother Road.",
    image: "/assets/part2/day2-joliet-pontiac.png",
    imageAlt: "Pixel-art Illinois Route 66 roadside scene with a giant spaceman and rental car",
    imageCaption: "ILLINOIS · THE MOTHER ROAD BEGINS",
    body: [
      "We landed at O'Hare before the city was properly awake, collected the Hertz car, and officially upgraded the trip from airport mode to road-trip mode.",
      "Breakfast at Lou Mitchell's was exactly the kind of old-school launch Route 66 deserves: coffee, diner energy, and enough history in the room to make our overnight flight feel almost respectable.",
      "We made a quick Chicago pass for the Route 66 beginning-of-the-road ritual, then aimed southwest toward Joliet. The welcome center and the old prison turned one stop into several because apparently we are incapable of merely driving through a historic town.",
      "The Gemini Giant was waiting in Wilmington with an American flag and a rocket, looking like roadside America had hired its own space program. This is the kind of completely unnecessary monument that makes Route 66 absolutely necessary.",
      "We added the restored Standard Oil station in Odell, then rolled into Pontiac for the night at the Hampton Inn—tired enough to stop, but already surrounded by murals and museum signs clearly plotting tomorrow's schedule.",
    ],
    stops: ["O'Hare International Airport · Hertz", "Lou Mitchell's", "Route 66 Begin Sign · Joliet Welcome Center · Old Joliet Prison", "Gemini Giant", "Odell Standard Oil Station · Hampton Inn Pontiac"],
  },
  {
    part: 2,
    day: 1,
    slug: "red-eye-to-route-66",
    title: "Red-Eye to Route 66",
    date: "2026-08-21",
    dateDisplay: "Aug 21, 2026",
    location: "San Francisco → Chicago",
    weather: "Mostly cloudy, 19/14°C.",
    summary: "Part II begins with CLEAR, carry-ons, a late gate upgrade sighting, and an overnight flight pointed straight at Chicago.",
    image: "/assets/part2/day1-red-eye.png",
    imageAlt: "Pixel-art late-night airport gate with an airplane waiting outside",
    imageCaption: "DEPARTURE · 10:53 PM",
    body: [
      "Part II began with the bold frontier move of taking an overnight flight from San Francisco to Chicago. The pioneers had wagons; we had boarding groups, a very specific carry-on strategy, and CLEAR plus TSA PreCheck moving us quickly through SFO—leaving plenty of time for the ancient airport ritual of staring at an unchanged gate screen.",
      "American Airlines flight AA2113 was scheduled for 10:53 p.m., with Chicago waiting at 5:13 in the morning. Near the end of boarding, a last-minute gate upgrade supplied a tiny burst of first-class drama while the rest of us continued toward row 22 and negotiated with an economy seat until sunrise. Tomorrow meant O'Hare, a rental car, Lou Mitchell's, and actual Route 66 pavement; tonight was cabin lights, airplane air, and the opening credits.",
    ],
    stops: ["San Francisco International Airport · CLEAR & TSA PreCheck", "American Airlines AA2113 · SFO → Chicago"],
  },
  {
    part: 1,
    day: 10,
    slug: "folk-art-fancy-coffee-bye-new-mexico",
    title: "Folk Art, Fancy Coffee, Bye New Mexico",
    date: "2026-02-21",
    dateDisplay: "Feb 21, 2026",
    location: "Albuquerque",
    weather: "Mostly cloudy, 15/-5°C.",
    summary: "Breakfast at Hotel Santa Fe, a stop at the Museum of International Folk Art, coffee at Iconik Lupe, then to ABQ for the flight leg back to PHX and SFO.",
    image: "/assets/part1/day10-santa-fe-albuquerque.webp",
    imageAlt: "Pixel-art Santa Fe folk-art courtyard and coffee stop leading toward Albuquerque airport",
    imageCaption: "SANTA FE → ALBUQUERQUE · FINAL LEG",
    body: [
      "We started the morning by doing the rarest thing on any trip: actually enjoying hotel breakfast.",
      "Hotel Santa Fe came through with a legit breakfast spread, good coffee, and zero regrets. Honestly, it set an unreasonably high bar for the rest of the day.",
      "From there we headed to the Museum of International Folk Art and wandered through room after room of pieces that somehow made us feel both cultured and underdressed.",
      "Then came the coffee mission in Lupe: the spot is Iconik Lupe on Guadalupe. Famous for a reason—strong coffee, cool vibe, and exactly the right amount of “we should probably be heading out” energy.",
      "After that, we made the push to ABQ (Albuquerque International Sunport) and got ready to fly back toward PHX and then SFO. Route 66 ground mission complete; airport mode activated.",
    ],
    stops: ["Hotel Santa Fe", "Museum of International Folk Art", "Iconik Lupe", "Albuquerque International Sunport"],
  },
  {
    part: 1,
    day: 9,
    slug: "downtown-santa-fe-miracle-staircase-happy-hour-timing",
    title: "Downtown Santa Fe Wandering, Miracle Staircase, and Happy Hour Timing",
    date: "2026-02-20",
    dateDisplay: "Feb 20, 2026",
    location: "Santa Fe",
    weather: "Sunny, 6/-9°C.",
    summary: "A downtown Santa Fe day with the Loretto miracle staircase, enchiladas and green chile stew, San Miguel Chapel, Canyon Road galleries, and a strategic happy-hour return.",
    image: "/assets/part1/day9-santa-fe-wandering.webp",
    imageAlt: "Pixel-art Santa Fe adobe streets with Loretto Chapel, galleries, and winter sunlight",
    imageCaption: "SANTA FE · DOWNTOWN WANDERING",
    body: [
      "Today was supposed to be a “light” day, which naturally turned into a full mission with a lot of walking and very confident snack logic.",
      "We spent most of the day wandering downtown Santa Fe, people-watching, ducking in and out of shops, and pretending we were “just browsing” while absolutely power-touring everything within a few blocks.",
      "We stopped at Loretto Chapel to see the famous miracle staircase in person. I can confirm: photos do not do it justice, and yes, everyone there has the same expression of “wait… how did they even build this?”",
      "Lunch was a proper New Mexico move at The Shed—enchiladas plus green chile stew, which was exactly the kind of meal that makes you rethink every bland lunch choice you've made in your life.",
      "After that we checked out San Miguel Chapel, then made our way through the Canyon Road art district. Lots of galleries, lots of “we should totally hang this at home” moments, and a shocking amount of self-control.",
      "We wrapped the day by heading back to Hotel Santa Fe with perfect timing for happy hour, which is the kind of elite logistical execution this trip deserves.",
    ],
    stops: ["Downtown Santa Fe", "Loretto Chapel", "The Shed", "San Miguel Chapel", "Canyon Road", "Hotel Santa Fe"],
  },
  {
    part: 1,
    day: 8,
    slug: "winslow-to-santa-fe-wigwam-throwback-maverik-save",
    title: "Winslow to Santa Fe, Wigwam Throwback, and a Maverik Save",
    date: "2026-02-19",
    dateDisplay: "Feb 19, 2026",
    location: "Santa Fe",
    weather: "Light snow, 2/-6°C.",
    summary: "Long haul from Winslow to Santa Fe with Wigwam nostalgia, a Maverik fuel save, a first Dairy Queen upside-down ice cream moment, and a cozy two-night stay at Hotel Santa Fe.",
    image: "/assets/part1/day8-winslow-santa-fe.webp",
    imageAlt: "Pixel-art Route 66 drive from Winslow past a wigwam motel toward snowy Santa Fe",
    imageCaption: "WINSLOW → SANTA FE · LONG HAUL",
    body: [
      "Today was the big push from Winslow to Santa Fe—the kind of drive where your playlist starts strong, then gets weird, then somehow circles back to confidence.",
      "We made a nostalgia detour at the Wigwam Motel in Holbrook, because if Route 66 offers you giant teepee rooms and retro roadside chaos, you say yes and ask questions never.",
      "Later, somewhere in “please let this gas gauge be lying” territory, Maverik (Gallup) came through like a roadside guardian angel with snacks, fuel, and the exact energy of “you're not stranded yet.”",
      "Before we officially called it a Santa Fe arrival, we stopped at Dairy Queen at the Casa Blanca gas station—my first time ever trying it. The employee did the legendary upside-down ice cream move like it was a magic trick, and honestly, I was way too impressed for a grown adult.",
      "Then we checked into Hotel Santa Fe, and it's seriously cozy. After a long haul day, this place felt like a reward, and we're staying here for two nights to reset before the next stretch.",
    ],
    stops: ["Winslow", "Wigwam Motel", "Maverik Gallup", "Dairy Queen Casa Blanca", "Hotel Santa Fe"],
  },
  {
    part: 1,
    day: 7,
    slug: "standing-around-winslow",
    title: "Flagstaff to Winslow, Corner Stop, and La Posada",
    date: "2026-02-18",
    dateDisplay: "Feb 18, 2026",
    location: "Winslow",
    weather: "Clear, 8.4/-3.2°C.",
    summary: "Short drive from Flagstaff to Winslow with a stop at Standin' on the Corner Park and an afternoon at La Posada Hotel and museum.",
    image: "/assets/part1/day7-winslow-la-posada.webp",
    imageAlt: "Pixel-art Winslow street corner and La Posada Hotel beneath a clear Arizona sky",
    imageCaption: "WINSLOW · STANDIN' ON THE CORNER",
    body: [
      "Today was a short hop from Flagstaff to Winslow—a nice break from the longer driving days and a chance to pretend we are “taking it easy” while still doing a full itinerary like absolute professionals.",
      "First stop in town was Standin' on the Corner Park. Classic Winslow energy. We did the mandatory gawking, photo ops, and “yes, this song is now permanently stuck in my head” moment.",
      "After that, we headed to La Posada Hotel—which is genuinely beautiful. Historic, full of character, and one of those places where every hallway makes you slow down and look around. We also spent time in the Affeldt Mion Museum there, which made the whole stop feel less like “quick overnight” and more like a proper destination.",
      "Short drive day, high vibes day, zero regrets day.",
    ],
    stops: ["Flagstaff", "Standin' on the Corner Park", "La Posada Hotel", "Affeldt Mion Museum"],
  },
  {
    part: 1,
    day: 6,
    slug: "snowy-white-knuckle-driving-frozen-flagstaff-wander",
    title: "Snowy White-Knuckle Driving and a Frozen Flagstaff Wander",
    date: "2026-02-17",
    dateDisplay: "Feb 17, 2026",
    location: "Flagstaff",
    weather: "Heavy snowfall, -1.2/-8.2°C.",
    summary: "Williams to Flagstaff in steady snow, a cold wander, and a warm meal at Little America.",
    image: "/assets/part1/day6-snowy-flagstaff.webp",
    imageAlt: "Pixel-art road-trip sedan driving through heavy snow toward Flagstaff's warm downtown lights",
    imageCaption: "WILLIAMS → FLAGSTAFF · WINTER ROAD",
    body: [
      "We drove from Williams to Flagstaff today and the weather decided to add a little drama: steady snow, gray skies, and the kind of road conditions that make you grip the wheel like it owes you money. I‑40 was slow but manageable—mostly a cautious parade of semis and SUVs—so we took it easy, watched for slick patches on bridges and overpasses, and enjoyed the surprisingly pretty snow-dusted pines once the nerves dialed down.",
      "Rolled into Flagstaff cold, relieved, and immediately in search of heat. And then (because we're apparently allergic to staying warm) we went over to the Riordan Mansion and did a wander through Heritage Square—with my hands absolutely freezing the entire time. 10/10 scenic winter vibes, 0/10 finger circulation.",
      "We capped it off by buying two pizzas for “afternoon tea,” which feels extremely correct in this climate: classy in spirit, feral in execution.",
      "And then we ended the day with a great meal inside Little America—warm, cozy, and exactly what our frozen souls needed.",
    ],
    stops: ["Williams", "Interstate 40", "Riordan Mansion", "Heritage Square", "Little America Flagstaff"],
  },
  {
    part: 1,
    day: 5,
    slug: "side-quests-seligman-kitsch-williams-deep-freeze",
    title: "Side Quests, Seligman Kitsch, and the Williams Deep Freeze",
    date: "2026-02-16",
    dateDisplay: "Feb 16, 2026",
    location: "Williams",
    weather: "Heavy snowfall, 2.3/-3.2°C.",
    summary: "Kingman museums + Bonelli House, then Hackberry, a stop at the old Truxton Canyon school site, Seligman kitsch, and on to Williams.",
    image: "/assets/part1/day5-kingman-williams.webp",
    imageAlt: "Pixel-art Route 66 roadside store and Seligman landmarks on the climb from Kingman to snowy Williams",
    imageCaption: "KINGMAN → WILLIAMS · ROADSIDE DETOURS",
    body: [
      "Started the morning in Kingman with a shockingly good Best Western breakfast (I know). Actual hot food, decent coffee, and waffles that didn't taste like foam packaging.",
      "Then we did the museum double-feature: the Route 66 Museum and the Mohave Museum—followed by a quick peek at the Bonelli House for some “people actually lived like this” energy.",
      "After that we rolled out to the Hackberry General Store, which is equal parts roadside shrine, gift shop, and nostalgia trap (in a good way).",
      "We made a quick stop at the old Truxton Canyon Training School site (Valentine's weirdly fascinating “how is this still here?” time capsule), then kept rolling.",
      "After that, we rolled through Seligman for a quick dose of classic Route 66 kitsch and then pointed the car toward Williams for the day (where the elevation politely reminds you that Arizona can, in fact, be cold).",
    ],
    stops: ["Best Western Kingman", "Arizona Route 66 Museum", "Mohave Museum", "Bonelli House", "Hackberry General Store", "Truxton Canyon Training School", "Seligman", "Williams"],
  },
  {
    part: 1,
    day: 4,
    slug: "oatman-donkey-parade-road-to-kingman",
    title: "Donkey Traffic Control in Oatman (and the Road to Kingman)",
    date: "2026-02-15",
    dateDisplay: "Feb 15, 2026",
    location: "Kingman",
    weather: "Moderate rain, 16.6/8.1°C.",
    summary: "Welcome to California sign, Oatman donkey chaos, then overnight in Kingman (and Mr D'z).",
    image: "/assets/part1/day4-oatman-kingman.webp",
    imageAlt: "Pixel-art wild burros blocking Oatman's rainy main street on the road to Kingman",
    imageCaption: "OATMAN · DONKEY TRAFFIC",
    body: [
      "Before Oatman, we pulled over at the Welcome to California Sign for a quick photo—because road trips are 40% driving and 60% proving you were there.",
      "Then we made it into Oatman, walked the old wooden sidewalks, and soaked in the full old-west vibe.",
      "The headline event was the donkey situation: donkeys everywhere, confidently occupying the road like local government officials.",
      "By evening we reached Kingman, checked in, and had dinner at Mr D'z Diner. We asked for a to-go box for our salad… and then completely forgot to take it. We even drove back for it, but the waitress had already tossed it—RIP salad, you were too pure for this journey. Sadly, both the burger and the steak were pretty underwhelming, so we called it early and let the donkeys keep running traffic operations without us.",
    ],
    stops: ["Welcome to California Sign", "Oatman", "Kingman", "Mr D'z Route 66 Diner"],
  },
  {
    part: 1,
    day: 3,
    slug: "bottle-trees-ghost-towns-neon-needles",
    title: "Bottle Trees, Ghost Towns, Neon Lights, and Needles",
    date: "2026-02-14",
    dateDisplay: "Feb 14, 2026",
    location: "Needles",
    weather: "Overcast, 24.1/13.9°C.",
    summary: "Museums in Barstow, then bottle trees, Calico, Bagdad Cafe, Roy's neon, and a one-night stop in Needles (plus River City Pizza).",
    image: "/assets/part1/day3-bottle-trees-needles.webp",
    imageAlt: "Pixel-art bottle trees, ghost-town buildings, and desert neon along Route 66 toward Needles",
    imageCaption: "HIGH DESERT · NEON & GHOST TOWNS",
    body: [
      "Day 3 was pure High Desert chaos in the best way: lots of stops, zero restraint.",
      "We kicked off in Barstow at the Mother Road Museum, then hit the Harvey House like responsible travelers who absolutely have a schedule and definitely stick to it.",
      "Next was Elmer's Bottle Tree Ranch in Oro Grande, where someone looked at a pile of bottles and said, “Yes, this is art,” and honestly, they were right.",
      "We rolled through Calico Ghost Town, stopped at Bagdad Cafe, and grabbed the classic photo at the Roy's Motel neon sign.",
      "By evening we reached Needles for the night. Gas on this stretch was slow and expensive, which was a fun little reminder that suffering builds character.",
      "We closed out with pizza at River City Pizza in Needles and called it a win.",
    ],
    stops: ["Barstow Mother Road Museum", "Harvey House", "Elmer's Bottle Tree Ranch", "Calico Ghost Town", "Bagdad Cafe", "Roy's Motel", "Needles", "River City Pizza"],
  },
  {
    part: 1,
    day: 2,
    slug: "pier-selfies-end-of-trail-barstow",
    title: "Pier Selfies, End-of-the-Trail Photos, and a Barstow Reality Check",
    date: "2026-02-13",
    dateDisplay: "Feb 13, 2026",
    location: "Barstow",
    weather: "Overcast, 20.2/4.4°C.",
    summary: "Santa Monica Pier, Pasadena smoothies, the End of the Trail sign, the original McDonald's museum, a Victorville museum stop, then rolling into Barstow.",
    image: "/assets/part1/day2-santa-monica-barstow.webp",
    imageAlt: "Pixel-art Santa Monica Pier and a Route 66 road-trip sedan heading inland toward Barstow",
    imageCaption: "SANTA MONICA · ROUTE 66 BEGINS",
    body: [
      "Day 2 finally looked like a real Route 66 day instead of an airport side quest.",
      "We started at Santa Monica Pier and got the mandatory End of the Trail Sign photo, because if there isn't photographic evidence, did the trip even happen?",
      "Then it was off to Pasadena for smoothies, followed by a stop at the Original McDonald's Museum—a historic site proving that road-trip nutrition has always been a flexible concept.",
      "We made a quick museum stop at the Route 66 Museum (Victorville), then tried Raising Cane's Chicken Fingers for the first time in the name of science.",
      "By night we rolled into Barstow, tired, overfed, and extremely confident in our ability to turn every stop into a full production.",
    ],
    stops: ["Santa Monica Pier", "End of the Trail Sign", "Pasadena", "Original McDonald's Museum", "California Route 66 Museum", "Barstow"],
  },
  {
    part: 1,
    day: 1,
    slug: "tsa-glamour-airport-limbo-mcnuggets",
    title: "TSA Glamour, Airport Limbo, and McNuggets",
    date: "2026-02-12",
    dateDisplay: "Feb 12, 2026",
    location: "Los Angeles",
    weather: "Overcast, 20.4/6.2°C.",
    summary: "Flew SJC to LAX, checked into Jamaica Bay Inn, and celebrated elite travel culture with McDonald's for dinner.",
    image: "/assets/part1/day1-sjc-lax.webp",
    imageAlt: "Pixel-art airport terminal overlooking a plane and the rainy Marina del Rey waterfront",
    imageCaption: "CALIFORNIA · AIRPORT LAUNCH",
    body: [
      "Day 1 of our legendary Route 66 road trip began with the bold, authentic road-warrior move of… flying from SJC to LAX.",
      "Nothing says “classic highway adventure” like TSA, gate changes, and paying airport prices for water like it's a collectible item.",
      "After landing at LAX, we checked into Jamaica Bay Inn and pretended this was all part of a highly strategic launch sequence.",
      "Dinner was McDonald's, because after navigating airport logistics, the Michelin guide can wait and fries cannot.",
      "Tomorrow: actual miles on Route 66, fewer boarding announcements, and hopefully less emotional damage from carry-on roulette.",
    ],
    stops: ["San Jose International Airport", "Los Angeles International Airport", "Jamaica Bay Inn"],
  },
];

export const getEntriesForPart = (part) => entries.filter((entry) => entry.part === part);

export const getEntryBySlug = (slug) => entries.find((entry) => entry.slug === slug);
